// ============================================
// Vercel Build Script — generates js/supabase.js
// from SUPABASE_URL and SUPABASE_ANON_KEY env vars
// set in Vercel Dashboard → Settings → Environment Variables
// ============================================

const fs = require('fs');
const path = require('path');

const url  = process.env.SUPABASE_URL      || 'YOUR_SUPABASE_URL';
const key  = process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

if (url === 'YOUR_SUPABASE_URL' || key === 'YOUR_SUPABASE_ANON_KEY') {
  console.warn(
    '⚠️  SUPABASE_URL / SUPABASE_ANON_KEY not set in environment.\n' +
    '   Add them in Vercel Dashboard → Settings → Environment Variables.'
  );
}

const content = `// ⚡ Auto-generated by scripts/build-config.js — do not edit manually
// Set SUPABASE_URL and SUPABASE_ANON_KEY in your Vercel environment variables.

const SUPABASE_URL      = "${url}";
const SUPABASE_ANON_KEY = "${key}";

let supabase;

try {
  if (window.supabase && window.supabase.createClient) {
    supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: {
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: true,
      },
      realtime: {
        params: {
          eventsPerSecond: 10,
        },
      },
    });
  } else {
    console.warn('Supabase SDK not loaded yet. Some features may not work.');
    supabase = null;
  }
} catch (e) {
  console.error('Supabase init failed:', e);
  supabase = null;
}

export default supabase;
export { SUPABASE_URL, SUPABASE_ANON_KEY };
`;

const outPath = path.join(__dirname, '../js/supabase.js');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, 'utf8');
console.log('✅ js/supabase.js generated successfully');
